name: Enforce labels on Pull Request
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "bug, enhancement, documentation, good first issue"
          add_comment: true
          message: "**Label error**. \n To merge the PR, it requires {{ errorString }} {{ count }} label indicating the type of PR.\n- The type-related labels available are: {{ provided }}.\n- Labels found: {{ applied }}."