name: "Pull Request Labeler"
on:
  workflow_dispatch:
  issues:
    types:
      - opened

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
